version: '3'

services:
  whatsapp-bot:
    build:
      context: .
    restart: unless-stopped
    environment:
      - SESSION_KEY=${SESSION_KEY}
      - PMPERMIT_ENABLED=${PMPERMIT_ENABLED}
      - MONGODB_URL=${MONGODB_URL}
      - DEFAULT_TR_LANG=${DEFAULT_TR_LANG}
      - ENABLE_DELETE_ALERT=${ENABLE_DELETE_ALERT}
      - TIMEZONE=${TIMEZONE}
      - OCR_SPACE_API_KEY=${OCR_SPACE_API_KEY}
